language: cpp
os:
- linux
- osx
env:
- PYTHON=2.7
- PYTHON=3.5
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    - kubuntu-backports
    packages:
    - g++-4.8
    - python3.5
    - python3.5-dev
    - cmake
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8 CC=gcc-4.8; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PYTHON" = "3.5" ]; then brew update; brew install python3; fi
- pip install --user virtualenv
- virtualenv -p python$PYTHON venv
- source venv/bin/activate
install:
- python setup.py sdist
- pip install dist/*.tar.gz
script:
- python tests/test.py
